# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: hsbc2_development
  pool: 5
  username: louis
  password:



production:
  adapter: postgresql
  host: ec2-54-217-208-46.eu-west-1.compute.amazonaws.com
  database: detkocfri7srd6
  user: unczqqvzlojmpw
  port: 5432
  password: B7D3rItlgMe3xMS2dTQR0ll4sE
